name: beauty_shop
description: "A Flutter Project for Final Exam"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  device_preview: ^1.2.0
  http: ^1.0.0
  image_picker: ^0.8.4+5
  mime: ^1.0.0
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for clean coding practices
  flutter_lints: ^4.0.0

  # Flutter Launcher Icons: Untuk mengatur icon aplikasi (opsional)
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/product_0.jpg
    - assets/images/product_1.jpg
    - assets/images/product_2.jpg
    - assets/images/product_3.jpg